[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "module-wifi"
version = "0.1.0"
description = "Wifi location module"
readme = "README.md"
authors = [
    { name = "Phillip Dickey", email = "pdickey@gmu.edu" },
#    { name = "Enzo Fernandez", email = "" },
#    { name = "Sasha Cherian", email = "" },
#    { name = "Khoi Le", email = "" },
]
requires-python = ">=3.11"

dependencies = [
    "ruff~=0.9.3",
    "comtypes>=1.4.10",
    "dotenv>=0.9.9",
    "geocoder>=1.38.1",
    "pywifi>=1.1.12",
    "requests>=2.32.3",
]

[tool.ruff.lint]
select = [
    "F",
    "E",
    "W",
    "C90",
    "I",
    "N",
    "UP",
    "ANN",
    "ASYNC",
    "C4",
]

[tool.setuptools.packages.find]
include = ["*"]