from enum import StrEnum
from types import MappingProxyType


ctrl_send_reg_msg="C_REG_MSG"

MSG_INT_STR_MAP: MappingProxyType = {
    0x00: "RESERVED_INVALID",
    0x01: "CURRENT_LOCATION",
    0x02: "MOVE_LOCATION",
    0x03: "ENABLE_JAMMER",
    0x04: "DISABLE_JAMMER",
    0x05: "ENABLE_RF_DECEPTION",
    0x06: "DISABLE_RF_DECEPTION",
    0x07: "CONTROLLER_ENABLE_REGISTRATION",
    0x08: "DRONE_CONFIRM_REGISTRATION"
}

MSG_STR_INT_MAP: MappingProxyType = { value: key for key, value in MSG_INT_STR_MAP.items()}

class MSG_STR_E(StrEnum):
        RESERVED_INVALID = "RESERVED_INVALID"
        CURRENT_LOCATION = "CURRENT_LOCATION"
        MOVE_LOCATION = "MOVE_LOCATION"
        ENABLE_JAMMER = "ENABLE_JAMMER"
        DISABLE_JAMMER = "DISABLE_JAMMER"
        ENABLE_RF_DECEPTION = "ENABLE_RF_DECEPTION"
        DISABLE_RF_DECEPTION = "DISABLE_RF_DECEPTION"
        CONTROLLER_ENABLE_REGISTRATION = "CONTROLLER_ENABLE_REGISTRATION"
        DRONE_CONFIRM_REGISTRATION = "DRONE_CONFIRM_REGISTRATION"
