# ruff: noqa: N801
from enum import StrEnum
from types import MappingProxyType

MSG_INT_STR_MAP: MappingProxyType[int, str] = {
    0x00: "RESERVED_INVALID",
    0x01: "CURRENT_LOCATION",
    0x02: "MOVE_LOCATION",
    0x03: "ENABLE_JAMMER",
    0x04: "DISABLE_JAMMER",
    0x05: "ENABLE_RF_DECEPTION",
    0x06: "DISABLE_RF_DECEPTION",
    0x07: "ENABLE_REGISTRATION",
    0x08: "CONFIRM_REGISTRATION",
}

MSG_STR_INT_MAP: MappingProxyType[str, int] = {
    "RESERVED_INVALID": 0x00,
    "CURRENT_LOCATION": 0x01,
    "MOVE_LOCATION": 0x02,
    "ENABLE_JAMMER": 0x03,
    "DISABLE_JAMMER": 0x04,
    "ENABLE_RF_DECEPTION": 0x05,
    "DISABLE_RF_DECEPTION": 0x06,
    "ENABLE_REGISTRATION": 0x07,
    "CONFIRM_REGISTRATION": 0x08,
}


class MSG_STR_E(StrEnum):
    RESERVED_INVALID = "RESERVED_INVALID"
    CURRENT_LOCATION = "CURRENT_LOCATION"
    MOVE_LOCATION = "MOVE_LOCATION"
    ENABLE_JAMMER = "ENABLE_JAMMER"
    DISABLE_JAMMER = "DISABLE_JAMMER"
    ENABLE_RF_DECEPTION = "ENABLE_RF_DECEPTION"
    DISABLE_RF_DECEPTION = "DISABLE_RF_DECEPTION"
    ENABLE_REGISTRATION = "ENABLE_REGISTRATION"
    CONFIRM_REGISTRATION = "CONFIRM_REGISTRATION"
